name: CI

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Add remote
        env:
          HF: ${{ secrets.HF }}
        run: git remote add space https://privacywithpavan:$HF@huggingface.co/spaces/privacywithpavan/mlops
      - name: Push to hub
        env:
          HF: ${{ secrets.HF }}
        run: git push --force https://privacywithpavan:$HF@huggingface.co/spaces/privacywithpavan/mlops main
